### ISSUE TITLE
increment_topnav does not work

### ISSUE THREAD

**Issue by mattmeye** [ignorantshr/mkdocs-add-number-plugin#15]
Hi, i need the configuration option "increment_topnav", but still get an error.

mkdocs.yml:

```
site_name: GitLab MkDocs Example

plugins:
  - add-number:
      increment_topnav: True
```

error:

`~\AppData\Roaming\Python\Python39\site-packages\mkdocs_add_number_plugin\plugin.py", line 51, in on_nav
    nav.items[index].title = str(index + 1) + '. ' + \
TypeError: can only concatenate str (not "NoneType") to str`
