### ISSUE TITLE
excludes parameter not working

### ISSUE THREAD

**Issue by timvink** [ignorantshr/mkdocs-add-number-plugin#8]
I tried setting:

```yml
- mkdocs-add-number-plugin:
    excludes: 
        - TMD/
```

But all the files is the folder still have the heading numbers added. 

Did this functionality work for you?

I could submit another PR to fix it (after first finishing #4)
